-- 코드를 입력하세요
SELECT RESULT.AUTHOR_ID,
       RESULT.AUTHOR_NAME,
       RESULT.CATEGORY,
       SUM(RESULT.PRICE * RESULT.SALES) AS TOTAL_SALES
FROM (
    SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE, B.BOOK_ID, BS.SALES, BS.SALES_DATE  
    FROM BOOK B
    INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    INNER JOIN (SELECT * FROM BOOK_SALES
                WHERE SALES_DATE BETWEEN '2022-01-01 00:00:00' AND '2022-01-31 23:59:59'
    ) BS ON B.BOOK_ID = BS.BOOK_ID
) RESULT
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
;

# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE, BS.SALES, BS.SALES_DATE
#     FROM BOOK B
#     INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
#     INNER JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID AND
#         BS.SALES_DATE BETWEEN '2022-01-01 00:00:00' AND '2022-01-31 23:59:59'
   # GROUP BY AUTHOR_NAME, CATEGORY
   
   # SELECT * FROM BOOK_SALES
   # WHERE SALES_DATE BETWEEN '2022-01-01 00:00:00' AND '2022-01-31 23:59:59'
   # ORDER BY BOOK_ID, SALES_DATE;